"""empty message

Revision ID: 3dd6da5f8d1d
Revises: 
Create Date: 2024-09-09 13:00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3dd6da5f8d1d'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Commands auto generated by Alembic - please adjust! 
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

def downgrade():
    # Commands auto generated by Alembic - please adjust! 
    op.drop_table('user')
