name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Güncel Python sürümünü kullanabilirsiniz
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        flask db upgrade
    - name: Run tests
      run: |
        # Install pytest or other testing tool
        pip install pytest
        # Run your tests here
        pytest
